load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "Connection",
    srcs = ["Connection.cpp"],
    hdrs = ["Connection.h"],
    visibility = ["//Server/NetworkServer:__pkg__"],
    deps = [ "//DataProtocol" ]
)
