load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "DataStore",
    srcs = ["DataStore.cpp"],
    hdrs = ["DataStore.h"],
    visibility = ["//Server/Main:__pkg__"],
    deps = ["//DataProtocol"],
)
