cc_binary(
    name = "Main",
    srcs = [ "Main.cpp" ],
    deps = [ 
        "//Client/CsvReader:CsvReader",
        "//Client/ResponseReceiver:ResponseReceiver",
        "//Client/NetworkClient:NetworkClient",
        "//DataProtocol:DataProtocol"
        ]
)