load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ResponseReceiver",
    srcs = ["ResponseReceiver.cpp"],
    hdrs = ["ResponseReceiver.h"],
    visibility = ["//Client/Main:__pkg__"],
)
