load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "LatencyProfiler",
    srcs = ["LatencyProfiler.cpp"],
    hdrs = ["LatencyProfiler.h", "json.hpp"],
    visibility = ["//visibility:public"],
)
