load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "LatencyProfile",
    srcs = ["LatencyProfile.cpp"],
    hdrs = ["LatencyProfile.h", "json.hpp"],
    visibility = ["//visibility:public"],
)
