load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "AverageCalculator",
    srcs = ["AverageCalculator.cpp"],
    hdrs = ["AverageCalculator.h"],
    visibility = ["//Server/Main:__pkg__"],
    deps = ["//DataProtocol"],
)
