cc_binary(
    name = "Main",
    srcs = [ "Main.cpp" ],
    deps = [ 
        "//Server/AverageCalculator:AverageCalculator",
        "//Server/DataStore:DataStore",
        "//Server/NetworkServer",
        "//DataProtocol:DataProtocol"
    ]
)